export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-light dark:bg-dark p-4">
      <div className="max-w-2xl mx-auto">
        <h1 className="text-3xl font-bold text-center text-dark dark:text-light mb-4">
          Privacy Policy
        </h1>
        <p className="text-center text-gray dark:text-light mb-4">
          Last updated: September 08, 2024
        </p>
        
        <p className="text-dark dark:text-light mb-4">
          This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>
        <p className="text-dark dark:text-light mb-4">
          We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. 
        </p>

        <h2 className="text-2xl font-semibold text-dark dark:text-light mb-3">Interpretation and Definitions</h2>

        <h3 className="text-xl font-semibold text-dark dark:text-light mb-2">Interpretation</h3>
        <p className="text-dark dark:text-light mb-4">
          The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
        </p>

        <h3 className="text-xl font-semibold text-dark dark:text-light mb-2">Definitions</h3>
        <p className="text-dark dark:text-light mb-4">For the purposes of this Privacy Policy:</p>

        <ul className="list-disc list-inside mb-4 text-dark dark:text-light">
          <li><strong>Account:</strong> means a unique account created for You to access our Service or parts of our Service.</li>
          <li><strong>Affiliate:</strong> means an entity that controls, is controlled by or is under common control with a party...</li>
          <li><strong>Company:</strong> refers to Punterss.</li>
          <li><strong>Cookies:</strong> are small files that are placed on Your computer, mobile device...</li>
          <li><strong>Country:</strong> refers to Zambia.</li>
          <li><strong>Device:</strong> means any device that can access the Service such as a computer, a cellphone...</li>
          <li><strong>Personal Data:</strong> is any information that relates to an identified or identifiable individual.</li>
          <li><strong>Service:</strong> refers to the Website.</li>
          <li><strong>Service Provider:</strong> means any natural or legal person who processes the data...</li>
          <li><strong>Usage Data:</strong> refers to data collected automatically, either generated by the use of the Service...</li>
        </ul>

        <h2 className="text-2xl font-semibold text-dark dark:text-light mb-3">Collecting and Using Your Personal Data</h2>

        <h3 className="text-xl font-semibold text-dark dark:text-light mb-2">Types of Data Collected</h3>
        
        <h4 className="text-lg font-semibold text-dark dark:text-light mb-2">Personal Data</h4>
        <p className="text-dark dark:text-light mb-4">
          While using Our Service, We may ask You to provide Us with certain personally identifiable information...
        </p>

        <h4 className="text-lg font-semibold text-dark dark:text-light mb-2">Usage Data</h4>
        <p className="text-dark dark:text-light mb-4">Usage Data is collected automatically when using the Service...</p>

        <h4 className="text-lg font-semibold text-dark dark:text-light mb-2">Tracking Technologies and Cookies</h4>
        <p className="text-dark dark:text-light mb-4">
          We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information...
        </p>

        <h3 className="text-xl font-semibold text-dark dark:text-light mb-2">Use of Your Personal Data</h3>
        <ul className="list-disc list-inside mb-4 text-dark dark:text-light">
          <li><strong>To provide and maintain our Service:</strong> including to monitor the usage of our Service.</li>
          <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service...</li>
          <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of communication...</li>
        </ul>

        <h2 className="text-2xl font-semibold text-dark dark:text-light mb-3">Contact Us</h2>
        <p className="text-dark dark:text-light mb-4">If you have any questions about this Privacy Policy, You can contact us:</p>

        <ul className="list-disc list-inside mb-4 text-dark dark:text-light">
          <li>By email: zulugeoffrey034@gmail.com</li>
        </ul>
      </div>
    </div>
  );
}
